languageCode = "en-us"
title = "Aftnet"
baseURL = "https://www.aftnet.net/"
canonifyURLs = true

[params]
  Author = "Alberto Fustinoni"
  Email = "alberto@aftnet.net"
  SiteDescription = "Alberto Fustinoni's homepage"
  TagLine = "Hello, my name is"
  JobDescription = "Product manager & developer"
  Thumbnail = "/assets/img/logo.png"
  Location = "Living in Tokyo, Japan"
  GoogleAnalyticsId = "UA-22182855-1"