languageCode = "en-us"
title = "Aftnet"
baseURL = "http://www.aftnet.net/"
canonifyURLs = true

[params]
  Author = "Alberto Fustinoni"
  Description = "Alberto Fustinoni's homepage"
  Tagline = "Product manager & developer"