languageCode = "en-us"
title = "Aftnet"
baseURL = "http://www.aftnet.net/"
canonifyURLs = true

[params]
  Author = "Alberto Fustinoni"
  Email = "alberto@aftnet.net"
  Description = "Alberto Fustinoni's homepage"
  Tagline = "Product manager & developer"
  Location = "Living in Tokyo, Japan"